GET http://localhost:8080/douyin/favorite/list/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYWEiLCJ1c2VyX2lkIjoiMTAwMiIsImV4cCI6MTY1MzkxMzg1N30.SD_iVFzXGOWwNdowuf12Nrk3ax0My0m-Zf9MSsiZwko&user_id=1002
