server:
  addr: 0.0.0.0:8080
  mode: debug

redis:
  addr: 127.0.0.1:6379
  password: ''
  db: 0

database:
  type: mysql
  #  type: sqlite
  user: root
  password: fly990712
  host: 127.0.0.1
  port: 3306
  database: test
  #  config: 'charset=utf8&parseTime=True&loc=Local'

  maxIdleConns: 10
  maxOpenConns: 100
  log: false
  autoMigrate: true

session:
  key: 'DY_SESSIONID'
  size: 10
  # 7 * 86400 7天
  maxAge: 604800
  path: '/'
  domain: ''
  httpOnly: true

minio:
  endpoint: "127.0.0.1:9000"
  accessKey: "minio"
  secretAccessKey: "minio123"
  useSSL: false
