server:
  port: 8080
  mode: 'release'

redis:
  Addr: '127.0.0.1:6379'
  password: '123456'
  db: 0

database:
  user: root
  password: '123456'
  path: '192.168.252.100:3306'
  database: 'test'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  driver: 'mysql'
  maxIdleConns: 10
  maxOpenConns: 100
  log: false
  autoMigrate: true

session:
  key: 'DY_SESSIONID'
  size: 10
  # 7 * 86400 7天
  maxAge: 604800
  path: '/'
  domain: ''
  httpOnly: true

minio:
  endpoint: "192.168.252.100:9000"
  accessKey: "minio"
  secretAccessKey: "minio123"
  useSSL: false
