server:
  port: 8080
  mode: 'release'

redis:
  Addr: '127.0.0.1:6379'   #自己redis的ip和端口
  password: ''            #自己redis的密码 ，一般为空没有设置密码
  db: 0                  #默认选择0号数据库

mysql:
  user: root
  password: 'ran123456'
  path: '127.0.0.1:3306'
  database: 'testdb'
  config: 'charset=utf8&parseTime=True&loc=Local'
  driver: 'mysql'
  maxIdleConns: 10
  maxOpenConns: 100
  log: false
  autoMigrate: false

session:
  key: 'DY_SESSIONID'
  size: 10
  # 7 * 86400 7天
  maxAge: 604800
  path: '/'
  domain: ''
  httpOnly: true